#!/bin/bash

exec nvidia-docker run \
    -v $(pwd):/work \
    -v ${DATA_CACHE:-$HOME/CACHE}:/cache \
    -w /work \
    -e DATA_PROXY="$DATA_PROXY" \
    --net host \
    -p 3128:3128 \
    -p 5999:5999 \
    -p 8888:8888 -ti ocropy "$@"
